#  1
name: Android CI
#  2
on:
  #  3
  push:
    #  4
    branches: [ "main", "master" ]
  #  5
  pull_request:
#  6
jobs:
  #  7
  build:
    #  8
    runs-on: ubuntu-latest
    #  9
    steps:
      # 10
      - name: Checkout
        # 11
        uses: actions/checkout@v4
      # 12
      - name: Set up JDK 17
        # 13
        uses: actions/setup-java@v4
        # 14
        with:
          # 15
          distribution: temurin
          # 16
          java-version: "17"
          # 17
          cache: gradle
      # 18
      - name: Set up Android SDK
        # 19
        uses: android-actions/setup-android@v3
        # 20
        with:
          # 21 — очень важно: отступ ровно 2 пробела под with:, ключи без кавычек
          accept-android-sdk-licenses: true
          # 22 — блоковое строковое значение. Никаких кавычек!
          packages: |
            # 24 (пример для compileSdk 34 и build-tools 34.0.0)
            # 25 ↓↓↓ Строки 34–36 должны быть выровнены ОДИНАКОВО (ровно 12 пробелов слева)
            # 26
            # 27
            # 28
            # 29
            # 30
            # 31
            # 32
            # 33
            platform-tools               # 34  ← вот здесь начиналась ошибка у тебя, проверь отступы и кавычки
            platforms;android-34         # 35
            build-tools;34.0.0           # 36
      # 37
      - name: Make gradlew executable
        # 38
        run: chmod +x ./gradlew
      # 39
      - name: Build Debug
        # 40
        run: ./gradlew assembleDebug --stacktrace
