name: ndk-build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nttld/setup-ndk@v1
        with: { ndk-version: r26d }
      - name: CMake (arm64)
        run: |
          cmake -S . -B build \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-21 \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake
          cmake --build build --config Release
      - uses: actions/upload-artifact@v4
        with: { name: bin-arm64, path: build }
