name: Build FFmpeg for Android

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [arm64-v8a, armeabi-v7a, x86_64, x86]

    steps:
      - uses: actions/checkout@v4

      - name: Set up NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r29  # Актуально на 2025; обновите если нужно

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y yasm cmake

      - name: Find CMakeLists.txt path
        id: find-cmake
        run: |
          CMAKE_PATH=$(find . -name CMakeLists.txt | head -1)
          if [ -z "$CMAKE_PATH" ]; then
            echo "Error: CMakeLists.txt not found in repository!"
            exit 1
          fi
          CMAKE_DIR=$(dirname $CMAKE_PATH)
          echo "Found CMakeLists.txt in $CMAKE_DIR"
          echo "cmake_dir=$CMAKE_DIR" >> $GITHUB_OUTPUT

      - name: Configure and Build CMake
        run: |
          cd ${{ steps.find-cmake.outputs.cmake_dir }}
          mkdir build-${{ matrix.abi }}
          cd build-${{ matrix.abi }}
          cmake .. -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
                   -DANDROID_ABI=${{ matrix.abi }} \
                   -DANDROID_PLATFORM=android-25 \
                   -DANDROID_NATIVE_API_LEVEL=25
          make -j$(nproc)

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-so-${{ matrix.abi }}
          path: ${{ steps.find-cmake.outputs.cmake_dir }}/build-${{ matrix.abi }}/libs/*.so  # Адаптируйте, если путь к .so другой